class Venta:

	def __init__(self, codigo, dia, mes, anio, codigo_vendedor, nombre_vendedor, codigo_cliente, nombre_cliente, codigo_producto, nombre_producto, valor_unitario, cantidad, total):

		self.codigo = codigo
		self.dia = dia
		self.mes = mes
		self.anio = anio
		self.codigo_vendedor = codigo_vendedor
		self.nombre_vendedor = nombre_vendedor
		self.codigo_cliente = codigo_cliente
		self.nombre_cliente = nombre_cliente
		self.codigo_producto = codigo_producto
		self.nombre_producto = nombre_producto
		self.valor_unitario = valor_unitario
		self.cantidad = cantidad
		self.total = total
		